# Generated by Django 2.1.5 on 2019-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaTourAllocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slot', models.IntegerField(unique=True)),
                ('player_holesplayed', models.IntegerField(blank=True, null=True)),
                ('player_score', models.IntegerField(blank=True, null=True)),
                ('player_stbl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-player_stbl'],
            },
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('HC', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='catalog/static/images/')),
                ('jacket', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='latourallocationmodel',
            name='player_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel'),
        ),
    ]
