# Generated by Django 2.1.5 on 2019-03-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190328_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaTourScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1_score', models.IntegerField(blank=True, null=True)),
                ('slot2_score', models.IntegerField(blank=True, null=True)),
                ('slot3_score', models.IntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.LaTourHoleModel')),
            ],
        ),
        migrations.CreateModel(
            name='LaTourStablefordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1_stbl', models.IntegerField(blank=True, null=True)),
                ('slot2_stbl', models.IntegerField(blank=True, null=True)),
                ('slot3_stbl', models.IntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.LaTourHoleModel')),
            ],
        ),
    ]
