# Generated by Django 2.1.5 on 2019-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190328_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/static/images/'),
        ),
    ]
