# Generated by Django 2.1.5 on 2019-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190328_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
